.TH MyCommand 1 "September 28, 2023" "Version 1.0" "My Command Manual"

.SH NAME
mycommand \- A simple command-line utility

.SH SYNOPSIS
.B mycommand
[\fIoptions\fR] \fIfile\fR

.SH DESCRIPTION
This is a brief description of what the mycommand utility does.

.PP
It might have multiple paragraphs.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help message.

.TP
.B \-v, \-\-version
Display version information.

.SH FILES
.I /etc/mycommand.conf
Default configuration file.

.SH SEE ALSO
.BR man (1),
.BR troff (1),
.BR groff (1).

.SH AUTHOR
Your Name <your.email@example.com>

.SH BUGS
No known bugs at this time.

.SH COPYRIGHT
Copyright © 2023 Your Company. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH REPORTING BUGS
Please report bugs to: <bug@example.com>

.SH NOTES
Additional notes or comments go here.
